version: '3.4'

services:

  catalog.db:
    container_name: catalog.db
    restart: always
    ports:
     - "27017:27017" 
    volumes:
     - mongo_data:/data/db 

  basket.db:
    container_name: basket.db
    restart: always
    ports:
     - "6379:6379"  
  
  discount.db:
    container_name: discount.db
    environment:
     - POSTGRES_PASSWORD=admin1234
     - POSTGRES_USER=admin
     - POSTGRES_DB=DiscountDb
    restart: always
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  pgadmin:
    container_name: pgadmin
    environment:
     - PGADMIN_DEFAULT_EMAIL=bufao@email.com
     - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - "5050:80" 
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalog.db:27017"
    ports:
      - "8000:80"
    depends_on:
     - catalog.db

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basket.db:6379"
      - "GrpcSettings:DiscountUrl=discount.grpc"
    ports:
      - "8001:80"
    depends_on:
      - basket.db

  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discount.db;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
    ports:
      - "8002:80"
    depends_on:
      - discount.db


  discount.grpc:
    container_name: discount.grpc 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discount.db;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
    ports:
      - "8003:80"
    depends_on:
      - discount.db